version: "3.9"

services:
  finetune:
    build: .
    container_name: finetune
    working_dir: /workspace
    volumes:
      - ./:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
