version: "3.9"

services:
  finetune:
    image: nvidia/cuda:12.6.2-cudnn8-runtime-ubuntu22.04
    container_name: finetune
    working_dir: /workspace
    volumes:
      - ./:/workspace
    command: bash -c "apt-get update && apt-get install -y python3-pip && pip3 install --upgrade pip && pip3 install -r requirements.txt && tail -f /dev/null"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
