version: "3.9"

# python3 -m venv /workspace/venv
# source /workspace/venv/bin/activate
# pip3 install -r requirements.txt
services:
  finetune:
    build: .
    working_dir: /workspace
    volumes:
      - ./:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: ["tail", "-f", "/dev/null"]
